namespace:
  name: monitoring
  labels:
    drasken.io/env: dev
    drasken.io/owner: platform

prometheus:
  name: prometheus
  image: prom/prometheus
  scrape_configs:
    - job_name: prometheus
      metrics_path: /metrics
      scrape_interval: 15s
      scrape_timeout: 15s
      static_configs:
        - targets:
            - localhost:9090

    - job_name: main-node
      metrics_path: /metrics
      scrape_interval: 15s
      scrape_timeout: 15s
      static_configs:
        - targets:
            - 51.83.6.157:9100

grafana:
  name: grafana
  image: grafana/grafana
  replicas: 3
  prometheusUrl: http://prometheus-0.prometheus:9090
  host: monitoring.drasken.cloud

mysql:
  name: mysql
  image: mysql
  replicas: 1
  rootPassword: Root@123
  database: grafana
  user: grafana
  password: Grafana@123
  storageSize: 20Gi
