apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.grafana.name}}-config
  namespace: {{.Values.namespace.name}}
data:
  prometheus.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: {{.Values.grafana.prometheusUrl}}
        isDefault: true
        editable: false
  dashboard.yml: |
    apiVersion: 1
    providers:
      - name: 'Drasken Labs Uptime Monitoring'
        orgId: 1
        folder: 'Uptime Monitoring'
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /etc/grafana/provisioning/dashboards
