apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.grafana.name}}-mysql-secret
  namespace: {{.Values.namespace.name}}
type: Opaque
stringData:
  GF_DATABASE_TYPE: mysql
  GF_DATABASE_HOST: "{{ .Values.mysql.name }}.{{ .Values.namespace.name }}.svc.cluster.local:3306"
  GF_DATABASE_NAME: {{.Values.mysql.database}}
  GF_DATABASE_USER: {{.Values.mysql.user}}
  GF_DATABASE_PASSWORD: {{.Values.mysql.password}}
