apiVersion: v1
kind: Service
metadata:
  name: {{.Values.grafana.name}}
  namespace: {{.Values.namespace.name}}
spec:
  selector:
    app: {{.Values.grafana.name}}
  ports:
    - name: http
      port: 3000
      targetPort: 3000
