apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.mysql.name}}-config
  namespace: {{.Values.namespace.name}}
data:
  my.cnf: |
    [mysqld]
    max_connections=300
    innodb_buffer_pool_size=512M
    innodb_flush_log_at_trx_commit=1
    sync_binlog=1
