apiVersion: v1
kind: Service
metadata:
  name: {{.Values.mysql.name}}
  namespace: {{.Values.namespace.name}}
spec:
  clusterIP: None
  ports:
    - port: 3306
      name: mysql
  selector:
    app: {{.Values.mysql.name}}
