apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.prometheus.name}}-config
  namespace: {{.Values.namespace.name}}
data:
  prometheus.yml: |
    scrape_configs:
{{ toYaml .Values.prometheus.scrape_configs | nindent 6 }}
