apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.prometheus.name}}-ingress
  namespace: {{.Values.namespace.name}}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: {{.Values.prometheus.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{.Values.prometheus.name}}
                port:
                  number: 9090
